version: '3.8'

services:
  # 主API服務
  api-server:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:3001"
    environment:
      - SANDBOX_GRPC_ADDRESS=sandbox-server:50051
      - DB_HOST=192.168.2.123
    depends_on:
      - sandbox-server
      # - postgres
    # networks:
    #   - app-network

  # Sandbox gRPC服務
  sandbox-server:
    build:
      context: .
      dockerfile: Dockerfile.sandbox
    ports:
      - "50051:50051"
    privileged: true  # isolate需要特權模式
    volumes:
      - /tmp:/tmp
    environment:
      - SANDBOX_COUNT=4
      - DB_HOST=192.168.2.123
    # networks:
    #   - app-network

  # PostgreSQL數據庫
#   postgres:
#     image: postgres:15
#     environment:
#       POSTGRES_DB: ojapi
#       POSTGRES_USER: ojapi
#       POSTGRES_PASSWORD: ojapi123
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     networks:
#       - app-network

# volumes:
#   postgres_data:

# networks:
#   app-network:
#     driver: bridge
