apiVersion: v1
kind: ConfigMap
metadata:
  name: oj-api-config
  namespace: oj-api
data:
  # 資料庫配置
  DB_HOST: "oj-api-postgres.orb.local"
  DB_PORT: "5432"
  DB_NAME: "ojapi"
  DB_USER: "ojapi"
  
  # Log 級別
  LOG_LEVEL: "info"
  
  # Gin 模式
  GIN_MODE: "release"
  
  # Sandbox 配置
  SANDBOX_COUNT: "4"
  ISOLATE_PATH: "/var/lib/isolate"
  
  # Scheduler 地址（API Server 的內部服務名稱）
  SCHEDULER_ADDRESS: "oj-api-server:3001"
  
  # OJ 配置（請根據實際環境修改）
  OJ_BASE_URL: "https://oj-api-mac.ruien.me"
  OJ_EXTERNAL_URL: "https://oj-api-mac.ruien.me"
  FRONTEND_URL: "https://oj-mac.ruien.me"
  
  # Gitea 配置（請根據實際環境修改）
  GIT_BASE_URL: "http://server.gitea.orb.local:3000"
  GIT_EXTERNAL_URL: "https://gitea-mac.ruien.me"
  GITEA_URL: "https://gitea-mac.ruien.me"
  GITEA_ISSUER: "https://gitea-mac.ruien.me"
