apiVersion: apps/v1
kind: Deployment
metadata:
  name: oj-sandbox-server
  namespace: oj-api
  labels:
    app: oj-sandbox-server
spec:
  replicas: 1  # Sandbox 可能需要較多資源，根據實際情況調整
  selector:
    matchLabels:
      app: oj-sandbox-server
  template:
    metadata:
      labels:
        app: oj-sandbox-server
    spec:
      containers:
      - name: sandbox
        image: heavenmanysugar/orangejuice-sandbox:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 50051
          name: grpc
          protocol: TCP
        env:
        # 從 ConfigMap 讀取環境變數
        - name: SANDBOX_COUNT
          valueFrom:
            configMapKeyRef:
              name: oj-api-config
              key: SANDBOX_COUNT
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: oj-api-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: oj-api-config
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: oj-api-config
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: oj-api-config
              key: DB_USER
        - name: SCHEDULER_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: oj-api-config
              key: SCHEDULER_ADDRESS
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: oj-api-config
              key: LOG_LEVEL
        - name: ISOLATE_PATH
          valueFrom:
            configMapKeyRef:
              name: oj-api-config
              key: ISOLATE_PATH
        # 從 Secret 讀取敏感資訊
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: oj-api-secret
              key: DB_PASSWORD
        # 特權模式和安全上下文 - isolate 需要
        securityContext:
          privileged: true
          capabilities:
            add:
            - SYS_ADMIN
            - SYS_CHROOT
        # Volume 掛載
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: isolate
          mountPath: /var/lib/isolate
        # 資源限制
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "2000m"
      volumes:
      - name: tmp
        emptyDir: {}
      - name: isolate
        emptyDir: {}
      # 如果使用私有 Registry，需要配置 imagePullSecrets
      # imagePullSecrets:
      # - name: registry-secret
